import 'package:proyecto/utils/app_string.dart';

Map<Strings, String> dictionaryEn = {
  Strings.loginTitle: "Login",
  Strings.loginOthersOptions: "Log in with one of the following options",
  Strings.loginEmailHint: "E-mail address",
  Strings.loginPasswordHint: "Password",
  Strings.loginButtonText: "Sign in",
  Strings.loginForgotPassword: "Forgot your password?",
  Strings.loginCreateAccount: "Don't have an account?",
  Strings.loginRememberMe: "Remember me",
  Strings.loginErrorEmail: "Enter a valid email address 'email@email.com'.",
  Strings.loginErrorPassword:
      "The password must be\n8 characters long\n1 uppercase\n1 lowercase\n1 number\n1 special character.",
  Strings.loginSingUpText: "Sign up",
  Strings.singUpTitle: "Sing Up",
  Strings.singUpOthersOptions: "Sing up with one of following options",
  Strings.singUpEmailHint: "Email",
  Strings.singUpNameHint: "Name",
  Strings.singUpPasswordHint: "Password",
  Strings.singUpRepeatPasswordHint: "Repeat password",
  Strings.singUpButtonText: "Create Account",
  Strings.loginEmailFail: "The email is not registered",
  Strings.loginPasswordFail: "The password is incorrect",
  Strings.failError: "An unexpected error has occurred",
  Strings.singUpPasswordNotCoincidence: "The passwords do not match",
  Strings.registerDisplayedNameError: "Enter a name",
  Strings.singUpEmailRepeatFail: "The email is already registered",
  Strings.cancelOperation: "Operation Canceled",
  Strings.settingsText: "Settings",
  Strings.settingsSystem: "System",
  Strings.settingsTheme: "Theme",
  Strings.singUpNewPasswordTitle: "Password",
  Strings.singUpNewPasswordSubtitle: "To continue you must create a password",
  Strings.settingsLanguaje: "Languaje",
  Strings.cancelButtonText: "Cancel",
  Strings.profileText: "Profile",
  Strings.signOutText: "Sign out",
  Strings.chanelTitle: "Chanel",
  Strings.chanelDescription: "Description",
  Strings.chanelButtonText: "Create Chanel",
  Strings.chanelName: "Name",
  Strings.chanelDescriptionError: "Enter a description",
  Strings.chanelFail: "The chanel already exists",
  Strings.editMessage: "Edit Message",
  Strings.addAdministrators: "Add Administrators",
  Strings.addUsers: "Add Users",
  Strings.deleteAdministrators: "Delete Administrators",
  Strings.deleteUsers: "Delete Users",
  Strings.administrators: "Administrators",
  Strings.users: "Users",
  Strings.addUserButtonText: "Add Users",
  Strings.deleteUsersText: "Delete Users",
  Strings.profile: "Profile",
  Strings.changePerfil: "Change Profile",
  Strings.changePassword: "Change Password",
  Strings.updateSuccess: "Update Success",
  Strings.updatePasswordSuccess: "Update Password Success",
  Strings.updatePasswordButton: "Update Password",
  Strings.noRememberMe: "There is no session stored",
  Strings.localizedReasonString: "Authenticate to access",
  Strings.lockedOutString: "API temporarily blocked due to too many attempts",
  Strings.notAvailableString:
      "The device does not have hardware support for biometric data",
  Strings.notEnrolledString: "No biometric data is found on the device",
  Strings.otherOperatingSystemString:
      "Operating system not compatible with biometric data",
  Strings.passcodeNotSetString: "No access code found on the device",
  Strings.permanentlyLockedOutString:
      "API permanently blocked due to too many attempts, enter your security pin or pattern",
  Strings.signInTitleString: "Stored session",
  Strings.cancelButtonString: "Cancel",
  Strings.goToSettingsButtonString: "Settings",
  Strings.biometricHintString: "Put your finger on the sensor",
  Strings.biometricNotRecognizedString: "unrecognized fingerprint",
  Strings.biometricSuccessString: "Recognized footprint",
  Strings.goToSettingsDescriptionString: "Please set your fingerprint",
};
