import 'package:proyecto/utils/app_string.dart';

Map<Strings, String> dictionaryEn = {
  Strings.loginTitle: "Login",
  Strings.loginOthersOptions: "Log in with one of the following options",
  Strings.loginEmailHint: "E-mail address",
  Strings.loginPasswordHint: "Password",
  Strings.loginButtonText: "Sign in",
  Strings.loginForgotPassword: "Forgot your password?",
  Strings.loginCreateAccount: "Don't have an account?",
  Strings.loginRememberMe: "Remember me",
  Strings.loginErrorEmail: "Enter a valid email address 'email@email.com'.",
  Strings.loginErrorPassword:
      "The password must be\n8 characters long\n1 uppercase\n1 lowercase\n1 number\n1 special character.",
  Strings.loginSingUpText: "Sign up",
  Strings.singUpTitle: "Sing Up",
  Strings.singUpOthersOptions: "Sing up with one of following options",
  Strings.singUpEmailHint: "Email",
  Strings.singUpNameHint: "Name",
  Strings.singUpPasswordHint: "Password",
  Strings.singUpRepeatPasswordHint: "Repeat password",
  Strings.singUpButtonText: "Create Account",
  Strings.loginEmailFail: "The email is not registered",
  Strings.loginPasswordFail: "The password is incorrect",
  Strings.failError: "An unexpected error has occurred",
  Strings.singUpPasswordNotCoincidence: "The passwords do not match",
  Strings.registerDisplayedNameError: "Enter a name",
  Strings.singUpEmailRepeatFail: "The email is already registered",
  Strings.cancelOperation: "Operation Canceled",
  Strings.settingsText: "Settings",
  Strings.settingsSystem: "System",
  Strings.settingsTheme: "Theme",
  Strings.singUpNewPasswordTitle: "Password",
  Strings.singUpNewPasswordSubtitle: "To continue you must create a password",
  Strings.settingsLanguaje: "Languaje",
};
