import 'package:proyecto/utils/app_string.dart';

Map<Strings, String> dictionaryEs = {
  Strings.loginTitle: "Inicio de sesión",
  Strings.loginOthersOptions:
      "Inicie sesión con una de las siguientes opciones",
  Strings.loginEmailHint: "correo electrónico",
  Strings.loginPasswordHint: "contraseña",
  Strings.loginButtonText: "Iniciar sesión",
  Strings.loginForgotPassword: "¿Olvidaste tu contraseña?",
  Strings.loginRememberMe: "Recordarme",
  Strings.loginCreateAccount: "Registrarse",
  Strings.loginErrorEmail:
      "Ingrese un correo Electronico valido 'email@email.com'",
  Strings.loginErrorPassword:
      "La contraseña debe tener\n8 caracteres\n1 mayuscula\n1 minuscula\n1 numero\n1 caracter especial",
  Strings.loginSingUpText: "Registrate",
  Strings.singUpTitle: "Registrarse",
  Strings.singUpOthersOptions: "Regístrese con una de las siguientes opciones",
  Strings.singUpEmailHint: "Correo electrónico",
  Strings.singUpNameHint: "Nombre",
  Strings.singUpPasswordHint: "Contraseña",
  Strings.singUpRepeatPasswordHint: "Repetir contraseña",
  Strings.singUpButtonText: "Crear cuenta",
  Strings.loginEmailFail: "El correo electrónico no esta registrado",
  Strings.loginPasswordFail: "La contraseña ingresada no coincide",
  Strings.failError: "Ocurrio un error inesperado",
  Strings.singUpPasswordNotCoincidence: "Las contraseñas no coinciden",
  Strings.registerDisplayedNameError: "Ingrese un Nombre",
  Strings.singUpEmailRepeatFail: "El correo electrónico ya esta registrado",
  Strings.cancelOperation: "Operación Cancelada",
  Strings.settingsText: "Configuración",
  Strings.settingsSystem: "Sistema",
  Strings.settingsTheme: "Tema",
  Strings.singUpNewPasswordTitle: "Contraseña",
  Strings.singUpNewPasswordSubtitle: "Para continuar debe crear una contraseña",
  Strings.settingsLanguaje: "Lenguaje",
  Strings.cancelButtonText: "Cancelar",
  Strings.profileText: "Perfil",
  Strings.signOutText: "Cerrar sesión",
  Strings.chanelTitle: "Canal",
  Strings.chanelDescription: "Descripción",
  Strings.chanelButtonText: "Crear canal",
  Strings.chanelName: "Nombre",
  Strings.chanelDescriptionError: "Ingrese una descripción",
  Strings.chanelFail: "El canal ya existe",
  Strings.editMessage: "Editar mensaje",
  Strings.addAdministrators: "Agregar administradores",
  Strings.addUsers: "Agregar usuarios",
  Strings.deleteAdministrators: "Eliminar administradores",
  Strings.deleteUsers: "Eliminar usuarios",
  Strings.administrators: "Administradores",
  Strings.users: "Usuarios",
  Strings.addUserButtonText: "Agregar usuarios",
  Strings.deleteUsersText: "Eliminar usuarios",
  Strings.profile: "Perfil",
  Strings.changePerfil: "Actualizar perfil",
  Strings.changePassword: "Cambiar contraseña",
  Strings.updateSuccess: "Actualización exitosa",
  Strings.updatePasswordSuccess: "Contraseña actualizada",
  Strings.updatePasswordButton: "Actualizar contraseña",
  Strings.noRememberMe: "No hay una sesión almacenada",
  Strings.localizedReasonString: "Autentiquese para acceder",
  Strings.lockedOutString:
      "API bloqueada temporalmente debido a demasiados intentos",
  Strings.notAvailableString:
      "El dispositivo no tiene soporte de hardware para datos biometricos",
  Strings.notEnrolledString:
      "No se encuentra ningun dato biometrico en el dispositivo",
  Strings.otherOperatingSystemString:
      "Sistema operativo no compatible con datos biometricos",
  Strings.passcodeNotSetString:
      "No se encuentra ningun codigo de acceso en el dispositivo",
  Strings.permanentlyLockedOutString:
      "API bloqueada permanentemente debido a demasiados intentos, coloque su pin o patron de seguridad",
  Strings.signInTitleString: "Sesión Almacenada",
  Strings.cancelButtonString: "Cancelar",
  Strings.goToSettingsButtonString: "Ajustes",
  Strings.biometricHintString: "Pon el dedo en el sensor",
  Strings.biometricNotRecognizedString: "Huella no reconocida",
  Strings.biometricSuccessString: "Huella reconocida",
  Strings.goToSettingsDescriptionString: "Por favor configure su huella",
};
